// Code generated by protoc-gen-go. DO NOT EDIT.
// source: license.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Rate_Unit int32

const (
	Rate_rps Rate_Unit = 0
	Rate_rpm Rate_Unit = 1
	Rate_rph Rate_Unit = 2
	Rate_rpd Rate_Unit = 3
	Rate_rpw Rate_Unit = 4
)

var Rate_Unit_name = map[int32]string{
	0: "rps",
	1: "rpm",
	2: "rph",
	3: "rpd",
	4: "rpw",
}

var Rate_Unit_value = map[string]int32{
	"rps": 0,
	"rpm": 1,
	"rph": 2,
	"rpd": 3,
	"rpw": 4,
}

func (x Rate_Unit) String() string {
	return proto.EnumName(Rate_Unit_name, int32(x))
}

func (Rate_Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{1, 0}
}

type Contract struct {
	Since                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=until,proto3" json:"until,omitempty"`
	Rate                 *Rate                `protobuf:"bytes,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Requests             uint32               `protobuf:"varint,4,opt,name=requests,proto3" json:"requests,omitempty"`
	Workplaces           uint32               `protobuf:"varint,5,opt,name=workplaces,proto3" json:"workplaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{0}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetSince() *timestamp.Timestamp {
	if m != nil {
		return m.Since
	}
	return nil
}

func (m *Contract) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

func (m *Contract) GetRate() *Rate {
	if m != nil {
		return m.Rate
	}
	return nil
}

func (m *Contract) GetRequests() uint32 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func (m *Contract) GetWorkplaces() uint32 {
	if m != nil {
		return m.Workplaces
	}
	return 0
}

type Rate struct {
	Value                uint32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit                 Rate_Unit `protobuf:"varint,2,opt,name=unit,proto3,enum=protobuf.Rate_Unit" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Rate) Reset()         { *m = Rate{} }
func (m *Rate) String() string { return proto.CompactTextString(m) }
func (*Rate) ProtoMessage()    {}
func (*Rate) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{1}
}
func (m *Rate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rate.Unmarshal(m, b)
}
func (m *Rate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rate.Marshal(b, m, deterministic)
}
func (m *Rate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rate.Merge(m, src)
}
func (m *Rate) XXX_Size() int {
	return xxx_messageInfo_Rate.Size(m)
}
func (m *Rate) XXX_DiscardUnknown() {
	xxx_messageInfo_Rate.DiscardUnknown(m)
}

var xxx_messageInfo_Rate proto.InternalMessageInfo

func (m *Rate) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Rate) GetUnit() Rate_Unit {
	if m != nil {
		return m.Unit
	}
	return Rate_rps
}

type RegisterLicenseRequest struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Contract             *Contract `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterLicenseRequest) Reset()         { *m = RegisterLicenseRequest{} }
func (m *RegisterLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterLicenseRequest) ProtoMessage()    {}
func (*RegisterLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{2}
}
func (m *RegisterLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLicenseRequest.Unmarshal(m, b)
}
func (m *RegisterLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLicenseRequest.Marshal(b, m, deterministic)
}
func (m *RegisterLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLicenseRequest.Merge(m, src)
}
func (m *RegisterLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterLicenseRequest.Size(m)
}
func (m *RegisterLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLicenseRequest proto.InternalMessageInfo

func (m *RegisterLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterLicenseRequest) GetContract() *Contract {
	if m != nil {
		return m.Contract
	}
	return nil
}

type RegisterLicenseResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterLicenseResponse) Reset()         { *m = RegisterLicenseResponse{} }
func (m *RegisterLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterLicenseResponse) ProtoMessage()    {}
func (*RegisterLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{3}
}
func (m *RegisterLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLicenseResponse.Unmarshal(m, b)
}
func (m *RegisterLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLicenseResponse.Marshal(b, m, deterministic)
}
func (m *RegisterLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLicenseResponse.Merge(m, src)
}
func (m *RegisterLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterLicenseResponse.Size(m)
}
func (m *RegisterLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLicenseResponse proto.InternalMessageInfo

func (m *RegisterLicenseResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateLicenseRequest struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Contract             *Contract `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateLicenseRequest) Reset()         { *m = CreateLicenseRequest{} }
func (m *CreateLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLicenseRequest) ProtoMessage()    {}
func (*CreateLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{4}
}
func (m *CreateLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLicenseRequest.Unmarshal(m, b)
}
func (m *CreateLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLicenseRequest.Marshal(b, m, deterministic)
}
func (m *CreateLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLicenseRequest.Merge(m, src)
}
func (m *CreateLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLicenseRequest.Size(m)
}
func (m *CreateLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLicenseRequest proto.InternalMessageInfo

func (m *CreateLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateLicenseRequest) GetContract() *Contract {
	if m != nil {
		return m.Contract
	}
	return nil
}

type CreateLicenseResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateLicenseResponse) Reset()         { *m = CreateLicenseResponse{} }
func (m *CreateLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLicenseResponse) ProtoMessage()    {}
func (*CreateLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{5}
}
func (m *CreateLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLicenseResponse.Unmarshal(m, b)
}
func (m *CreateLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLicenseResponse.Marshal(b, m, deterministic)
}
func (m *CreateLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLicenseResponse.Merge(m, src)
}
func (m *CreateLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLicenseResponse.Size(m)
}
func (m *CreateLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLicenseResponse proto.InternalMessageInfo

func (m *CreateLicenseResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateLicenseResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ReadLicenseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLicenseRequest) Reset()         { *m = ReadLicenseRequest{} }
func (m *ReadLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLicenseRequest) ProtoMessage()    {}
func (*ReadLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{6}
}
func (m *ReadLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLicenseRequest.Unmarshal(m, b)
}
func (m *ReadLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLicenseRequest.Marshal(b, m, deterministic)
}
func (m *ReadLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLicenseRequest.Merge(m, src)
}
func (m *ReadLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLicenseRequest.Size(m)
}
func (m *ReadLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLicenseRequest proto.InternalMessageInfo

func (m *ReadLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadLicenseResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Contract             *Contract            `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadLicenseResponse) Reset()         { *m = ReadLicenseResponse{} }
func (m *ReadLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*ReadLicenseResponse) ProtoMessage()    {}
func (*ReadLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{7}
}
func (m *ReadLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLicenseResponse.Unmarshal(m, b)
}
func (m *ReadLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLicenseResponse.Marshal(b, m, deterministic)
}
func (m *ReadLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLicenseResponse.Merge(m, src)
}
func (m *ReadLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_ReadLicenseResponse.Size(m)
}
func (m *ReadLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLicenseResponse proto.InternalMessageInfo

func (m *ReadLicenseResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadLicenseResponse) GetContract() *Contract {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *ReadLicenseResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ReadLicenseResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ReadLicenseResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type UpdateLicenseRequest struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Contract             *Contract `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateLicenseRequest) Reset()         { *m = UpdateLicenseRequest{} }
func (m *UpdateLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLicenseRequest) ProtoMessage()    {}
func (*UpdateLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{8}
}
func (m *UpdateLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLicenseRequest.Unmarshal(m, b)
}
func (m *UpdateLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLicenseRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLicenseRequest.Merge(m, src)
}
func (m *UpdateLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLicenseRequest.Size(m)
}
func (m *UpdateLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLicenseRequest proto.InternalMessageInfo

func (m *UpdateLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateLicenseRequest) GetContract() *Contract {
	if m != nil {
		return m.Contract
	}
	return nil
}

type UpdateLicenseResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateLicenseResponse) Reset()         { *m = UpdateLicenseResponse{} }
func (m *UpdateLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLicenseResponse) ProtoMessage()    {}
func (*UpdateLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{9}
}
func (m *UpdateLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLicenseResponse.Unmarshal(m, b)
}
func (m *UpdateLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLicenseResponse.Marshal(b, m, deterministic)
}
func (m *UpdateLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLicenseResponse.Merge(m, src)
}
func (m *UpdateLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLicenseResponse.Size(m)
}
func (m *UpdateLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLicenseResponse proto.InternalMessageInfo

func (m *UpdateLicenseResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateLicenseResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type DeleteLicenseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLicenseRequest) Reset()         { *m = DeleteLicenseRequest{} }
func (m *DeleteLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLicenseRequest) ProtoMessage()    {}
func (*DeleteLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{10}
}
func (m *DeleteLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLicenseRequest.Unmarshal(m, b)
}
func (m *DeleteLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLicenseRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLicenseRequest.Merge(m, src)
}
func (m *DeleteLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLicenseRequest.Size(m)
}
func (m *DeleteLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLicenseRequest proto.InternalMessageInfo

func (m *DeleteLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteLicenseResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteLicenseResponse) Reset()         { *m = DeleteLicenseResponse{} }
func (m *DeleteLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteLicenseResponse) ProtoMessage()    {}
func (*DeleteLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{11}
}
func (m *DeleteLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLicenseResponse.Unmarshal(m, b)
}
func (m *DeleteLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLicenseResponse.Marshal(b, m, deterministic)
}
func (m *DeleteLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLicenseResponse.Merge(m, src)
}
func (m *DeleteLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteLicenseResponse.Size(m)
}
func (m *DeleteLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLicenseResponse proto.InternalMessageInfo

func (m *DeleteLicenseResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteLicenseResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type RestoreLicenseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreLicenseRequest) Reset()         { *m = RestoreLicenseRequest{} }
func (m *RestoreLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreLicenseRequest) ProtoMessage()    {}
func (*RestoreLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{12}
}
func (m *RestoreLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreLicenseRequest.Unmarshal(m, b)
}
func (m *RestoreLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreLicenseRequest.Marshal(b, m, deterministic)
}
func (m *RestoreLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreLicenseRequest.Merge(m, src)
}
func (m *RestoreLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreLicenseRequest.Size(m)
}
func (m *RestoreLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreLicenseRequest proto.InternalMessageInfo

func (m *RestoreLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RestoreLicenseResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RestoreLicenseResponse) Reset()         { *m = RestoreLicenseResponse{} }
func (m *RestoreLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreLicenseResponse) ProtoMessage()    {}
func (*RestoreLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{13}
}
func (m *RestoreLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreLicenseResponse.Unmarshal(m, b)
}
func (m *RestoreLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreLicenseResponse.Marshal(b, m, deterministic)
}
func (m *RestoreLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreLicenseResponse.Merge(m, src)
}
func (m *RestoreLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreLicenseResponse.Size(m)
}
func (m *RestoreLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreLicenseResponse proto.InternalMessageInfo

func (m *RestoreLicenseResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RestoreLicenseResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{14}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type AddEmployeeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Employee             string   `protobuf:"bytes,2,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEmployeeRequest) Reset()         { *m = AddEmployeeRequest{} }
func (m *AddEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*AddEmployeeRequest) ProtoMessage()    {}
func (*AddEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{15}
}
func (m *AddEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEmployeeRequest.Unmarshal(m, b)
}
func (m *AddEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *AddEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEmployeeRequest.Merge(m, src)
}
func (m *AddEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_AddEmployeeRequest.Size(m)
}
func (m *AddEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEmployeeRequest proto.InternalMessageInfo

func (m *AddEmployeeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddEmployeeRequest) GetEmployee() string {
	if m != nil {
		return m.Employee
	}
	return ""
}

type DeleteEmployeeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Employee             string   `protobuf:"bytes,2,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEmployeeRequest) Reset()         { *m = DeleteEmployeeRequest{} }
func (m *DeleteEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEmployeeRequest) ProtoMessage()    {}
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{16}
}
func (m *DeleteEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEmployeeRequest.Unmarshal(m, b)
}
func (m *DeleteEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEmployeeRequest.Merge(m, src)
}
func (m *DeleteEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEmployeeRequest.Size(m)
}
func (m *DeleteEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEmployeeRequest proto.InternalMessageInfo

func (m *DeleteEmployeeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteEmployeeRequest) GetEmployee() string {
	if m != nil {
		return m.Employee
	}
	return ""
}

type AddWorkplaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Workplace            string   `protobuf:"bytes,2,opt,name=workplace,proto3" json:"workplace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWorkplaceRequest) Reset()         { *m = AddWorkplaceRequest{} }
func (m *AddWorkplaceRequest) String() string { return proto.CompactTextString(m) }
func (*AddWorkplaceRequest) ProtoMessage()    {}
func (*AddWorkplaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{17}
}
func (m *AddWorkplaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWorkplaceRequest.Unmarshal(m, b)
}
func (m *AddWorkplaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWorkplaceRequest.Marshal(b, m, deterministic)
}
func (m *AddWorkplaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWorkplaceRequest.Merge(m, src)
}
func (m *AddWorkplaceRequest) XXX_Size() int {
	return xxx_messageInfo_AddWorkplaceRequest.Size(m)
}
func (m *AddWorkplaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWorkplaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWorkplaceRequest proto.InternalMessageInfo

func (m *AddWorkplaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddWorkplaceRequest) GetWorkplace() string {
	if m != nil {
		return m.Workplace
	}
	return ""
}

type DeleteWorkplaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Workplace            string   `protobuf:"bytes,2,opt,name=workplace,proto3" json:"workplace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWorkplaceRequest) Reset()         { *m = DeleteWorkplaceRequest{} }
func (m *DeleteWorkplaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteWorkplaceRequest) ProtoMessage()    {}
func (*DeleteWorkplaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{18}
}
func (m *DeleteWorkplaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWorkplaceRequest.Unmarshal(m, b)
}
func (m *DeleteWorkplaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWorkplaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteWorkplaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWorkplaceRequest.Merge(m, src)
}
func (m *DeleteWorkplaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteWorkplaceRequest.Size(m)
}
func (m *DeleteWorkplaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWorkplaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWorkplaceRequest proto.InternalMessageInfo

func (m *DeleteWorkplaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteWorkplaceRequest) GetWorkplace() string {
	if m != nil {
		return m.Workplace
	}
	return ""
}

type PushWorkplaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Workplace            string   `protobuf:"bytes,2,opt,name=workplace,proto3" json:"workplace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushWorkplaceRequest) Reset()         { *m = PushWorkplaceRequest{} }
func (m *PushWorkplaceRequest) String() string { return proto.CompactTextString(m) }
func (*PushWorkplaceRequest) ProtoMessage()    {}
func (*PushWorkplaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{19}
}
func (m *PushWorkplaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushWorkplaceRequest.Unmarshal(m, b)
}
func (m *PushWorkplaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushWorkplaceRequest.Marshal(b, m, deterministic)
}
func (m *PushWorkplaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushWorkplaceRequest.Merge(m, src)
}
func (m *PushWorkplaceRequest) XXX_Size() int {
	return xxx_messageInfo_PushWorkplaceRequest.Size(m)
}
func (m *PushWorkplaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushWorkplaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushWorkplaceRequest proto.InternalMessageInfo

func (m *PushWorkplaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PushWorkplaceRequest) GetWorkplace() string {
	if m != nil {
		return m.Workplace
	}
	return ""
}

func init() {
	proto.RegisterType((*Contract)(nil), "protobuf.Contract")
	proto.RegisterType((*Rate)(nil), "protobuf.Rate")
	proto.RegisterType((*RegisterLicenseRequest)(nil), "protobuf.RegisterLicenseRequest")
	proto.RegisterType((*RegisterLicenseResponse)(nil), "protobuf.RegisterLicenseResponse")
	proto.RegisterType((*CreateLicenseRequest)(nil), "protobuf.CreateLicenseRequest")
	proto.RegisterType((*CreateLicenseResponse)(nil), "protobuf.CreateLicenseResponse")
	proto.RegisterType((*ReadLicenseRequest)(nil), "protobuf.ReadLicenseRequest")
	proto.RegisterType((*ReadLicenseResponse)(nil), "protobuf.ReadLicenseResponse")
	proto.RegisterType((*UpdateLicenseRequest)(nil), "protobuf.UpdateLicenseRequest")
	proto.RegisterType((*UpdateLicenseResponse)(nil), "protobuf.UpdateLicenseResponse")
	proto.RegisterType((*DeleteLicenseRequest)(nil), "protobuf.DeleteLicenseRequest")
	proto.RegisterType((*DeleteLicenseResponse)(nil), "protobuf.DeleteLicenseResponse")
	proto.RegisterType((*RestoreLicenseRequest)(nil), "protobuf.RestoreLicenseRequest")
	proto.RegisterType((*RestoreLicenseResponse)(nil), "protobuf.RestoreLicenseResponse")
	proto.RegisterType((*EmptyResponse)(nil), "protobuf.EmptyResponse")
	proto.RegisterType((*AddEmployeeRequest)(nil), "protobuf.AddEmployeeRequest")
	proto.RegisterType((*DeleteEmployeeRequest)(nil), "protobuf.DeleteEmployeeRequest")
	proto.RegisterType((*AddWorkplaceRequest)(nil), "protobuf.AddWorkplaceRequest")
	proto.RegisterType((*DeleteWorkplaceRequest)(nil), "protobuf.DeleteWorkplaceRequest")
	proto.RegisterType((*PushWorkplaceRequest)(nil), "protobuf.PushWorkplaceRequest")
	proto.RegisterEnum("protobuf.Rate_Unit", Rate_Unit_name, Rate_Unit_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LicenseClient is the client API for License service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LicenseClient interface {
	Register(ctx context.Context, in *RegisterLicenseRequest, opts ...grpc.CallOption) (*RegisterLicenseResponse, error)
	Create(ctx context.Context, in *CreateLicenseRequest, opts ...grpc.CallOption) (*CreateLicenseResponse, error)
	Read(ctx context.Context, in *ReadLicenseRequest, opts ...grpc.CallOption) (*ReadLicenseResponse, error)
	Update(ctx context.Context, in *UpdateLicenseRequest, opts ...grpc.CallOption) (*UpdateLicenseResponse, error)
	Delete(ctx context.Context, in *DeleteLicenseRequest, opts ...grpc.CallOption) (*DeleteLicenseResponse, error)
	Restore(ctx context.Context, in *RestoreLicenseRequest, opts ...grpc.CallOption) (*RestoreLicenseResponse, error)
	AddEmployee(ctx context.Context, in *AddEmployeeRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	DeleteEmployee(ctx context.Context, in *DeleteEmployeeRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	AddWorkplace(ctx context.Context, in *AddWorkplaceRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	DeleteWorkplace(ctx context.Context, in *DeleteWorkplaceRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	PushWorkplace(ctx context.Context, in *PushWorkplaceRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type licenseClient struct {
	cc *grpc.ClientConn
}

func NewLicenseClient(cc *grpc.ClientConn) LicenseClient {
	return &licenseClient{cc}
}

func (c *licenseClient) Register(ctx context.Context, in *RegisterLicenseRequest, opts ...grpc.CallOption) (*RegisterLicenseResponse, error) {
	out := new(RegisterLicenseResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Create(ctx context.Context, in *CreateLicenseRequest, opts ...grpc.CallOption) (*CreateLicenseResponse, error) {
	out := new(CreateLicenseResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Read(ctx context.Context, in *ReadLicenseRequest, opts ...grpc.CallOption) (*ReadLicenseResponse, error) {
	out := new(ReadLicenseResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Update(ctx context.Context, in *UpdateLicenseRequest, opts ...grpc.CallOption) (*UpdateLicenseResponse, error) {
	out := new(UpdateLicenseResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Delete(ctx context.Context, in *DeleteLicenseRequest, opts ...grpc.CallOption) (*DeleteLicenseResponse, error) {
	out := new(DeleteLicenseResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Restore(ctx context.Context, in *RestoreLicenseRequest, opts ...grpc.CallOption) (*RestoreLicenseResponse, error) {
	out := new(RestoreLicenseResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) AddEmployee(ctx context.Context, in *AddEmployeeRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/AddEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) DeleteEmployee(ctx context.Context, in *DeleteEmployeeRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/DeleteEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) AddWorkplace(ctx context.Context, in *AddWorkplaceRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/AddWorkplace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) DeleteWorkplace(ctx context.Context, in *DeleteWorkplaceRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/DeleteWorkplace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) PushWorkplace(ctx context.Context, in *PushWorkplaceRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protobuf.License/PushWorkplace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LicenseServer is the server API for License service.
type LicenseServer interface {
	Register(context.Context, *RegisterLicenseRequest) (*RegisterLicenseResponse, error)
	Create(context.Context, *CreateLicenseRequest) (*CreateLicenseResponse, error)
	Read(context.Context, *ReadLicenseRequest) (*ReadLicenseResponse, error)
	Update(context.Context, *UpdateLicenseRequest) (*UpdateLicenseResponse, error)
	Delete(context.Context, *DeleteLicenseRequest) (*DeleteLicenseResponse, error)
	Restore(context.Context, *RestoreLicenseRequest) (*RestoreLicenseResponse, error)
	AddEmployee(context.Context, *AddEmployeeRequest) (*EmptyResponse, error)
	DeleteEmployee(context.Context, *DeleteEmployeeRequest) (*EmptyResponse, error)
	AddWorkplace(context.Context, *AddWorkplaceRequest) (*EmptyResponse, error)
	DeleteWorkplace(context.Context, *DeleteWorkplaceRequest) (*EmptyResponse, error)
	PushWorkplace(context.Context, *PushWorkplaceRequest) (*EmptyResponse, error)
}

func RegisterLicenseServer(s *grpc.Server, srv LicenseServer) {
	s.RegisterService(&_License_serviceDesc, srv)
}

func _License_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Register(ctx, req.(*RegisterLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Create(ctx, req.(*CreateLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Read(ctx, req.(*ReadLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Update(ctx, req.(*UpdateLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Delete(ctx, req.(*DeleteLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Restore(ctx, req.(*RestoreLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_AddEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).AddEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/AddEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).AddEmployee(ctx, req.(*AddEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_DeleteEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).DeleteEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/DeleteEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).DeleteEmployee(ctx, req.(*DeleteEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_AddWorkplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWorkplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).AddWorkplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/AddWorkplace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).AddWorkplace(ctx, req.(*AddWorkplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_DeleteWorkplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).DeleteWorkplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/DeleteWorkplace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).DeleteWorkplace(ctx, req.(*DeleteWorkplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_PushWorkplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushWorkplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).PushWorkplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.License/PushWorkplace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).PushWorkplace(ctx, req.(*PushWorkplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _License_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.License",
	HandlerType: (*LicenseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _License_Register_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _License_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _License_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _License_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _License_Delete_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _License_Restore_Handler,
		},
		{
			MethodName: "AddEmployee",
			Handler:    _License_AddEmployee_Handler,
		},
		{
			MethodName: "DeleteEmployee",
			Handler:    _License_DeleteEmployee_Handler,
		},
		{
			MethodName: "AddWorkplace",
			Handler:    _License_AddWorkplace_Handler,
		},
		{
			MethodName: "DeleteWorkplace",
			Handler:    _License_DeleteWorkplace_Handler,
		},
		{
			MethodName: "PushWorkplace",
			Handler:    _License_PushWorkplace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "license.proto",
}

func init() { proto.RegisterFile("license.proto", fileDescriptor_090c1f856632b222) }

var fileDescriptor_090c1f856632b222 = []byte{
	// 834 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xda, 0x48,
	0x14, 0x5e, 0x8c, 0x21, 0x70, 0xb2, 0x10, 0x34, 0x21, 0x09, 0x6b, 0x91, 0xc0, 0xce, 0xae, 0x36,
	0x59, 0xb4, 0xc2, 0x59, 0x72, 0xb5, 0x7b, 0x55, 0x94, 0xa4, 0x57, 0xbd, 0xa8, 0xac, 0xa6, 0xed,
	0x5d, 0x65, 0xf0, 0x94, 0xb8, 0x05, 0xdb, 0xb5, 0x87, 0x44, 0xf9, 0x93, 0xaa, 0x5e, 0xf4, 0x05,
	0xfa, 0x5e, 0xbd, 0xe9, 0x2b, 0xf4, 0x35, 0x2a, 0x55, 0x9e, 0x19, 0xc3, 0xd8, 0xb1, 0x43, 0x50,
	0x72, 0xc5, 0x98, 0xf9, 0xce, 0xf9, 0xbe, 0x73, 0x8e, 0xcf, 0x67, 0xa8, 0x8c, 0xed, 0x21, 0x71,
	0x02, 0xd2, 0xf5, 0x7c, 0x97, 0xba, 0xa8, 0xc4, 0x7e, 0x06, 0xd3, 0xb7, 0x5a, 0x73, 0xe4, 0xba,
	0xa3, 0x31, 0xd1, 0x4d, 0xcf, 0xd6, 0x4d, 0xc7, 0x71, 0xa9, 0x49, 0x6d, 0xd7, 0x09, 0x38, 0x4e,
	0x6b, 0x89, 0xdb, 0x08, 0xae, 0x53, 0x7b, 0x42, 0x02, 0x6a, 0x4e, 0x3c, 0x0e, 0xc0, 0x5f, 0x73,
	0x50, 0x3a, 0x74, 0x1d, 0xea, 0x9b, 0x43, 0x8a, 0xf6, 0xa1, 0x10, 0xd8, 0xce, 0x90, 0x34, 0x72,
	0xed, 0xdc, 0xde, 0x6a, 0x4f, 0xeb, 0xf2, 0xe8, 0x6e, 0x14, 0xdd, 0x7d, 0x11, 0x45, 0x1b, 0x1c,
	0x18, 0x46, 0x4c, 0x1d, 0x6a, 0x8f, 0x1b, 0xca, 0xe2, 0x08, 0x06, 0x44, 0x18, 0x54, 0xdf, 0xa4,
	0xa4, 0x91, 0x67, 0x01, 0xd5, 0x39, 0xd2, 0x30, 0x29, 0x31, 0xd8, 0x1d, 0xd2, 0xa0, 0xe4, 0x93,
	0x0f, 0x53, 0x12, 0xd0, 0xa0, 0xa1, 0xb6, 0x73, 0x7b, 0x15, 0x63, 0xf6, 0x8c, 0x76, 0x00, 0xce,
	0x5d, 0xff, 0xbd, 0x37, 0x36, 0x87, 0x24, 0x68, 0x14, 0xd8, 0xad, 0xf4, 0x0f, 0xbe, 0x04, 0x35,
	0xcc, 0x84, 0xea, 0x50, 0x38, 0x33, 0xc7, 0x53, 0x5e, 0x4b, 0xc5, 0xe0, 0x0f, 0x68, 0x17, 0xd4,
	0xa9, 0x63, 0x53, 0x26, 0xb7, 0xda, 0x5b, 0x8f, 0xb3, 0x77, 0x4f, 0x1c, 0x9b, 0x1a, 0x0c, 0x80,
	0x0f, 0x40, 0x0d, 0x9f, 0xd0, 0x0a, 0xe4, 0x7d, 0x2f, 0xa8, 0xfd, 0xc2, 0x0f, 0x93, 0x5a, 0x8e,
	0x1f, 0x4e, 0x6b, 0x0a, 0x3f, 0x58, 0xb5, 0x3c, 0x3f, 0x9c, 0xd7, 0x54, 0xfc, 0x1a, 0x36, 0x0d,
	0x32, 0xb2, 0x03, 0x4a, 0xfc, 0x67, 0x7c, 0x5c, 0x06, 0x97, 0x8d, 0xaa, 0xa0, 0xd8, 0x16, 0x93,
	0x52, 0x36, 0x14, 0xdb, 0x42, 0x5d, 0x28, 0x0d, 0x45, 0xd7, 0x45, 0xeb, 0xd0, 0x5c, 0x4b, 0x34,
	0x0f, 0x63, 0x86, 0xc1, 0x7f, 0xc3, 0xd6, 0xad, 0xcc, 0x81, 0xe7, 0x3a, 0x01, 0x49, 0xa6, 0xc6,
	0x2f, 0xa1, 0x7e, 0xe8, 0x13, 0x93, 0x92, 0x47, 0x96, 0x30, 0x80, 0x8d, 0x44, 0xde, 0x74, 0x01,
	0xe8, 0x3f, 0x80, 0x21, 0x03, 0x5a, 0x6f, 0x4c, 0x7a, 0x8f, 0x17, 0xa3, 0x2c, 0xd0, 0x7d, 0x8a,
	0xff, 0x04, 0x64, 0x10, 0xd3, 0xba, 0x5b, 0x39, 0xfe, 0xac, 0xc0, 0x7a, 0x0c, 0x96, 0x21, 0x64,
	0xc9, 0x0a, 0x13, 0xc2, 0xf3, 0x4b, 0x08, 0x0f, 0x43, 0xa7, 0x9e, 0x15, 0x85, 0xaa, 0x8b, 0x43,
	0x05, 0x9a, 0x87, 0x5a, 0x64, 0x4c, 0x44, 0x68, 0x61, 0x71, 0xa8, 0x40, 0xf7, 0x69, 0x38, 0xea,
	0x13, 0x96, 0xe7, 0xf1, 0x47, 0x9d, 0xc8, 0x9b, 0x3d, 0x6a, 0xa9, 0x6c, 0x65, 0x89, 0xb2, 0xf1,
	0x5f, 0x50, 0x3f, 0x62, 0x85, 0x2c, 0x18, 0xf6, 0x00, 0x36, 0x12, 0xb8, 0x6c, 0x2d, 0x52, 0x1f,
	0x95, 0x65, 0xfa, 0xb8, 0x0b, 0x1b, 0x06, 0x09, 0xa8, 0xeb, 0x2f, 0x12, 0x33, 0x0c, 0x17, 0x3c,
	0x0e, 0x7c, 0xfc, 0xce, 0xac, 0x41, 0xe5, 0x78, 0xe2, 0xd1, 0x8b, 0x28, 0x37, 0x7e, 0x02, 0xa8,
	0x6f, 0x59, 0xc7, 0x13, 0x6f, 0xec, 0x5e, 0x90, 0xcc, 0x21, 0x6b, 0x50, 0x22, 0x02, 0xc2, 0xf8,
	0xca, 0xc6, 0xec, 0x19, 0x1f, 0x46, 0x4d, 0x7c, 0x58, 0x92, 0xf5, 0xbe, 0x65, 0xbd, 0x8a, 0xac,
	0x36, 0x2b, 0x45, 0x13, 0xca, 0x33, 0x3b, 0x16, 0x39, 0xe6, 0x7f, 0xe0, 0xa7, 0xb0, 0xc9, 0x95,
	0x3c, 0x30, 0xcf, 0x11, 0xd4, 0x9f, 0x4f, 0x83, 0xd3, 0x87, 0x65, 0xe9, 0xfd, 0x28, 0xc3, 0x8a,
	0x98, 0x24, 0xa2, 0x50, 0x8a, 0x2c, 0x16, 0xb5, 0xa5, 0x0f, 0x43, 0xaa, 0xa1, 0x6b, 0xbf, 0xdf,
	0x81, 0x10, 0x63, 0xfb, 0xe3, 0xd3, 0xb7, 0xef, 0x5f, 0x94, 0x6d, 0xdc, 0x60, 0xdf, 0xe6, 0xb3,
	0x7f, 0x75, 0xf1, 0x09, 0xd7, 0x7d, 0x11, 0xf0, 0x7f, 0xae, 0x83, 0x08, 0x14, 0xb9, 0xab, 0xa2,
	0x1d, 0x69, 0x25, 0x53, 0xfc, 0x5b, 0x6b, 0x65, 0xde, 0x0b, 0x3e, 0x8d, 0xf1, 0xd5, 0xf1, 0x5a,
	0x82, 0x2f, 0xa4, 0x31, 0x41, 0x0d, 0x1d, 0x13, 0x35, 0x65, 0xd9, 0x49, 0xa3, 0xd5, 0xb6, 0x33,
	0x6e, 0x05, 0x41, 0x93, 0x11, 0x6c, 0xa2, 0x7a, 0xb2, 0xa0, 0x2b, 0xdb, 0xba, 0x41, 0xef, 0xa0,
	0xc8, 0x4d, 0x43, 0xae, 0x24, 0xcd, 0x9e, 0xe4, 0x4a, 0x52, 0x6d, 0x06, 0xb7, 0x18, 0xd1, 0x6f,
	0x5a, 0x2a, 0x51, 0x58, 0xce, 0x08, 0x8a, 0xfc, 0x2d, 0x92, 0xb9, 0xd2, 0xec, 0x44, 0xe6, 0x4a,
	0xb5, 0x91, 0xa8, 0xa8, 0x4e, 0x56, 0x51, 0x2b, 0x62, 0xe1, 0x51, 0x4b, 0x6e, 0x4e, 0x8a, 0x59,
	0x68, 0xed, 0x6c, 0x40, 0x9c, 0xab, 0x97, 0xce, 0x75, 0x06, 0xab, 0xd2, 0x9a, 0xcb, 0xa3, 0xba,
	0xbd, 0xfd, 0xda, 0xd6, 0xfc, 0x36, 0x6e, 0x16, 0xfb, 0x8c, 0xa3, 0x83, 0xf7, 0xd2, 0x38, 0xf4,
	0x68, 0x99, 0xf5, 0xab, 0xe8, 0x74, 0x83, 0xae, 0xa1, 0x1a, 0x37, 0x07, 0x74, 0xab, 0x69, 0xcb,
	0xb2, 0x77, 0xee, 0xcf, 0x7e, 0x09, 0xbf, 0xca, 0xae, 0x82, 0xb6, 0x63, 0x65, 0x27, 0xf7, 0x3b,
	0x9b, 0xb9, 0xc7, 0x98, 0xff, 0xc1, 0x9d, 0x54, 0xe6, 0xd9, 0xca, 0xeb, 0x57, 0xb3, 0xe3, 0x0d,
	0xfa, 0x98, 0x83, 0xb5, 0x84, 0x1b, 0xc9, 0xab, 0x9f, 0x6e, 0x54, 0x0b, 0x25, 0x74, 0x96, 0x91,
	0x70, 0x0d, 0x95, 0x98, 0x8f, 0xc9, 0x2f, 0x74, 0x9a, 0xc1, 0x2d, 0x64, 0xd7, 0x96, 0x60, 0x1f,
	0x14, 0x59, 0xae, 0x83, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xe2, 0x25, 0x17, 0x5e, 0x0c,
	0x00, 0x00,
}
