archive:
  files:
  - LICENSE
  format: tar.gz
  format_overrides:
  - goos:   windows
    format: zip
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    386:     32bit
    amd64:   64bit
    darwin:  macOS
    linux:   Linux
    windows: Windows

brew:
  caveats: Use `--help` to see detailed help message
  commit_author:
    name:  Kamil Samigullin
    email: kamil@samigullin.info
  description: Access Control as a Service
  folder: Formula
  github:
    name:  homebrew-tap
    owner: kamilsk
  homepage: https://kamilsk.github.io/guard/

builds:
- binary: guard
  env:
  - CGO_ENABLED=0
  goarch:
  - 386
  - amd64
  goos:
  - darwin
  - linux
  - windows
  ldflags:
  - -s -w -X {{.Env.META}}.version={{.Version}} -X {{.Env.META}}.commit={{.Commit}} -X {{.Env.META}}.date={{.Date}}
  main: ./cmd/guard/main.go
- binary: guardctl
  env:
  - CGO_ENABLED=0
  flags:
  - -tags=ctl
  goarch:
  - 386
  - amd64
  goos:
  - darwin
  - linux
  - windows
  ldflags:
  - -s -w -X {{.Env.META}}.version={{.Version}} -X {{.Env.META}}.commit={{.Commit}} -X {{.Env.META}}.date={{.Date}}
  main: ./cmd/guardctl/main.go

checksum: { name_template: checksums.txt }

project_name: guard

release:
  draft: false
  github:
    name:  guard
    owner: kamilsk
