TRUNCATE TABLE "account" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "license" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "license_audit" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "license_employee" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "license_workplace" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "token" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "user" RESTART IDENTITY RESTRICT;
