// Code generated by protoc-gen-go. DO NOT EDIT.
// source: license.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterLicenseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterLicenseRequest) Reset()         { *m = RegisterLicenseRequest{} }
func (m *RegisterLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterLicenseRequest) ProtoMessage()    {}
func (*RegisterLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_license_ba62cf06d07d94eb, []int{0}
}
func (m *RegisterLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLicenseRequest.Unmarshal(m, b)
}
func (m *RegisterLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLicenseRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLicenseRequest.Merge(dst, src)
}
func (m *RegisterLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterLicenseRequest.Size(m)
}
func (m *RegisterLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLicenseRequest proto.InternalMessageInfo

type RegisterLicenseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterLicenseResponse) Reset()         { *m = RegisterLicenseResponse{} }
func (m *RegisterLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterLicenseResponse) ProtoMessage()    {}
func (*RegisterLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_license_ba62cf06d07d94eb, []int{1}
}
func (m *RegisterLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLicenseResponse.Unmarshal(m, b)
}
func (m *RegisterLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLicenseResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLicenseResponse.Merge(dst, src)
}
func (m *RegisterLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterLicenseResponse.Size(m)
}
func (m *RegisterLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLicenseResponse proto.InternalMessageInfo

type ExtendLicenseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtendLicenseRequest) Reset()         { *m = ExtendLicenseRequest{} }
func (m *ExtendLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*ExtendLicenseRequest) ProtoMessage()    {}
func (*ExtendLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_license_ba62cf06d07d94eb, []int{2}
}
func (m *ExtendLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtendLicenseRequest.Unmarshal(m, b)
}
func (m *ExtendLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtendLicenseRequest.Marshal(b, m, deterministic)
}
func (dst *ExtendLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtendLicenseRequest.Merge(dst, src)
}
func (m *ExtendLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_ExtendLicenseRequest.Size(m)
}
func (m *ExtendLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtendLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExtendLicenseRequest proto.InternalMessageInfo

type ExtendLicenseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtendLicenseResponse) Reset()         { *m = ExtendLicenseResponse{} }
func (m *ExtendLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*ExtendLicenseResponse) ProtoMessage()    {}
func (*ExtendLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_license_ba62cf06d07d94eb, []int{3}
}
func (m *ExtendLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtendLicenseResponse.Unmarshal(m, b)
}
func (m *ExtendLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtendLicenseResponse.Marshal(b, m, deterministic)
}
func (dst *ExtendLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtendLicenseResponse.Merge(dst, src)
}
func (m *ExtendLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_ExtendLicenseResponse.Size(m)
}
func (m *ExtendLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtendLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExtendLicenseResponse proto.InternalMessageInfo

type CheckLicenseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLicenseRequest) Reset()         { *m = CheckLicenseRequest{} }
func (m *CheckLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*CheckLicenseRequest) ProtoMessage()    {}
func (*CheckLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_license_ba62cf06d07d94eb, []int{4}
}
func (m *CheckLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLicenseRequest.Unmarshal(m, b)
}
func (m *CheckLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLicenseRequest.Marshal(b, m, deterministic)
}
func (dst *CheckLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLicenseRequest.Merge(dst, src)
}
func (m *CheckLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_CheckLicenseRequest.Size(m)
}
func (m *CheckLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLicenseRequest proto.InternalMessageInfo

type CheckLicenseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLicenseResponse) Reset()         { *m = CheckLicenseResponse{} }
func (m *CheckLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*CheckLicenseResponse) ProtoMessage()    {}
func (*CheckLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_license_ba62cf06d07d94eb, []int{5}
}
func (m *CheckLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLicenseResponse.Unmarshal(m, b)
}
func (m *CheckLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLicenseResponse.Marshal(b, m, deterministic)
}
func (dst *CheckLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLicenseResponse.Merge(dst, src)
}
func (m *CheckLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_CheckLicenseResponse.Size(m)
}
func (m *CheckLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLicenseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterLicenseRequest)(nil), "grpc.RegisterLicenseRequest")
	proto.RegisterType((*RegisterLicenseResponse)(nil), "grpc.RegisterLicenseResponse")
	proto.RegisterType((*ExtendLicenseRequest)(nil), "grpc.ExtendLicenseRequest")
	proto.RegisterType((*ExtendLicenseResponse)(nil), "grpc.ExtendLicenseResponse")
	proto.RegisterType((*CheckLicenseRequest)(nil), "grpc.CheckLicenseRequest")
	proto.RegisterType((*CheckLicenseResponse)(nil), "grpc.CheckLicenseResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LicenseClient is the client API for License service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LicenseClient interface {
	Register(ctx context.Context, in *RegisterLicenseRequest, opts ...grpc.CallOption) (*RegisterLicenseResponse, error)
	Extend(ctx context.Context, in *ExtendLicenseRequest, opts ...grpc.CallOption) (*ExtendLicenseResponse, error)
	Check(ctx context.Context, in *CheckLicenseRequest, opts ...grpc.CallOption) (*CheckLicenseResponse, error)
}

type licenseClient struct {
	cc *grpc.ClientConn
}

func NewLicenseClient(cc *grpc.ClientConn) LicenseClient {
	return &licenseClient{cc}
}

func (c *licenseClient) Register(ctx context.Context, in *RegisterLicenseRequest, opts ...grpc.CallOption) (*RegisterLicenseResponse, error) {
	out := new(RegisterLicenseResponse)
	err := c.cc.Invoke(ctx, "/grpc.License/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Extend(ctx context.Context, in *ExtendLicenseRequest, opts ...grpc.CallOption) (*ExtendLicenseResponse, error) {
	out := new(ExtendLicenseResponse)
	err := c.cc.Invoke(ctx, "/grpc.License/Extend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Check(ctx context.Context, in *CheckLicenseRequest, opts ...grpc.CallOption) (*CheckLicenseResponse, error) {
	out := new(CheckLicenseResponse)
	err := c.cc.Invoke(ctx, "/grpc.License/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LicenseServer is the server API for License service.
type LicenseServer interface {
	Register(context.Context, *RegisterLicenseRequest) (*RegisterLicenseResponse, error)
	Extend(context.Context, *ExtendLicenseRequest) (*ExtendLicenseResponse, error)
	Check(context.Context, *CheckLicenseRequest) (*CheckLicenseResponse, error)
}

func RegisterLicenseServer(s *grpc.Server, srv LicenseServer) {
	s.RegisterService(&_License_serviceDesc, srv)
}

func _License_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.License/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Register(ctx, req.(*RegisterLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Extend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Extend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.License/Extend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Extend(ctx, req.(*ExtendLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.License/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Check(ctx, req.(*CheckLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _License_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.License",
	HandlerType: (*LicenseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _License_Register_Handler,
		},
		{
			MethodName: "Extend",
			Handler:    _License_Extend_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _License_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "license.proto",
}

func init() { proto.RegisterFile("license.proto", fileDescriptor_license_ba62cf06d07d94eb) }

var fileDescriptor_license_ba62cf06d07d94eb = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xc9, 0x4c, 0x4e,
	0xcd, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56,
	0x92, 0xe0, 0x12, 0x0b, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x49, 0x2d, 0xf2, 0x81, 0x48, 0x07, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x49, 0x72, 0x89, 0x63, 0xc8, 0x14, 0x17, 0xe4, 0xe7, 0x15,
	0xa7, 0x2a, 0x89, 0x71, 0x89, 0xb8, 0x56, 0x94, 0xa4, 0xe6, 0xa5, 0xa0, 0x69, 0x11, 0xe7, 0x12,
	0x45, 0x13, 0x87, 0x6a, 0x10, 0xe5, 0x12, 0x76, 0xce, 0x48, 0x4d, 0xce, 0x46, 0x53, 0x2f, 0xc6,
	0x25, 0x82, 0x2a, 0x0c, 0x51, 0x6e, 0x74, 0x9b, 0x91, 0x8b, 0x1d, 0x2a, 0x26, 0xe4, 0xc9, 0xc5,
	0x01, 0x73, 0x86, 0x90, 0x8c, 0x1e, 0xc8, 0xcd, 0x7a, 0xd8, 0x1d, 0x2c, 0x25, 0x8b, 0x43, 0x16,
	0xea, 0x06, 0x06, 0x21, 0x67, 0x2e, 0x36, 0x88, 0xf3, 0x84, 0xa4, 0x20, 0x4a, 0xb1, 0x79, 0x42,
	0x4a, 0x1a, 0xab, 0x1c, 0xdc, 0x10, 0x07, 0x2e, 0x56, 0xb0, 0x9b, 0x85, 0x24, 0x21, 0xea, 0xb0,
	0xf8, 0x4b, 0x4a, 0x0a, 0x9b, 0x14, 0xcc, 0x84, 0x24, 0x36, 0x70, 0xf8, 0x1b, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0x17, 0x8e, 0x9d, 0x90, 0x01, 0x00, 0x00,
}
