// Code generated by protoc-gen-go. DO NOT EDIT.
// source: license.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateLicenseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLicenseRequest) Reset()         { *m = CreateLicenseRequest{} }
func (m *CreateLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLicenseRequest) ProtoMessage()    {}
func (*CreateLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{0}
}
func (m *CreateLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLicenseRequest.Unmarshal(m, b)
}
func (m *CreateLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLicenseRequest.Marshal(b, m, deterministic)
}
func (m *CreateLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLicenseRequest.Merge(m, src)
}
func (m *CreateLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLicenseRequest.Size(m)
}
func (m *CreateLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLicenseRequest proto.InternalMessageInfo

func (m *CreateLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateLicenseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLicenseResponse) Reset()         { *m = CreateLicenseResponse{} }
func (m *CreateLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLicenseResponse) ProtoMessage()    {}
func (*CreateLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{1}
}
func (m *CreateLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLicenseResponse.Unmarshal(m, b)
}
func (m *CreateLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLicenseResponse.Marshal(b, m, deterministic)
}
func (m *CreateLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLicenseResponse.Merge(m, src)
}
func (m *CreateLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLicenseResponse.Size(m)
}
func (m *CreateLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLicenseResponse proto.InternalMessageInfo

type ReadLicenseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLicenseRequest) Reset()         { *m = ReadLicenseRequest{} }
func (m *ReadLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLicenseRequest) ProtoMessage()    {}
func (*ReadLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{2}
}
func (m *ReadLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLicenseRequest.Unmarshal(m, b)
}
func (m *ReadLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLicenseRequest.Marshal(b, m, deterministic)
}
func (m *ReadLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLicenseRequest.Merge(m, src)
}
func (m *ReadLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLicenseRequest.Size(m)
}
func (m *ReadLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLicenseRequest proto.InternalMessageInfo

func (m *ReadLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadLicenseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLicenseResponse) Reset()         { *m = ReadLicenseResponse{} }
func (m *ReadLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*ReadLicenseResponse) ProtoMessage()    {}
func (*ReadLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{3}
}
func (m *ReadLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLicenseResponse.Unmarshal(m, b)
}
func (m *ReadLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLicenseResponse.Marshal(b, m, deterministic)
}
func (m *ReadLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLicenseResponse.Merge(m, src)
}
func (m *ReadLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_ReadLicenseResponse.Size(m)
}
func (m *ReadLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLicenseResponse proto.InternalMessageInfo

type UpdateLicenseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLicenseRequest) Reset()         { *m = UpdateLicenseRequest{} }
func (m *UpdateLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLicenseRequest) ProtoMessage()    {}
func (*UpdateLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{4}
}
func (m *UpdateLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLicenseRequest.Unmarshal(m, b)
}
func (m *UpdateLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLicenseRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLicenseRequest.Merge(m, src)
}
func (m *UpdateLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLicenseRequest.Size(m)
}
func (m *UpdateLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLicenseRequest proto.InternalMessageInfo

func (m *UpdateLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateLicenseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLicenseResponse) Reset()         { *m = UpdateLicenseResponse{} }
func (m *UpdateLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLicenseResponse) ProtoMessage()    {}
func (*UpdateLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{5}
}
func (m *UpdateLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLicenseResponse.Unmarshal(m, b)
}
func (m *UpdateLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLicenseResponse.Marshal(b, m, deterministic)
}
func (m *UpdateLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLicenseResponse.Merge(m, src)
}
func (m *UpdateLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLicenseResponse.Size(m)
}
func (m *UpdateLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLicenseResponse proto.InternalMessageInfo

type DeleteLicenseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLicenseRequest) Reset()         { *m = DeleteLicenseRequest{} }
func (m *DeleteLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLicenseRequest) ProtoMessage()    {}
func (*DeleteLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{6}
}
func (m *DeleteLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLicenseRequest.Unmarshal(m, b)
}
func (m *DeleteLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLicenseRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLicenseRequest.Merge(m, src)
}
func (m *DeleteLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLicenseRequest.Size(m)
}
func (m *DeleteLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLicenseRequest proto.InternalMessageInfo

func (m *DeleteLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteLicenseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLicenseResponse) Reset()         { *m = DeleteLicenseResponse{} }
func (m *DeleteLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteLicenseResponse) ProtoMessage()    {}
func (*DeleteLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{7}
}
func (m *DeleteLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLicenseResponse.Unmarshal(m, b)
}
func (m *DeleteLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLicenseResponse.Marshal(b, m, deterministic)
}
func (m *DeleteLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLicenseResponse.Merge(m, src)
}
func (m *DeleteLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteLicenseResponse.Size(m)
}
func (m *DeleteLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLicenseResponse proto.InternalMessageInfo

type RegisterLicenseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterLicenseRequest) Reset()         { *m = RegisterLicenseRequest{} }
func (m *RegisterLicenseRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterLicenseRequest) ProtoMessage()    {}
func (*RegisterLicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{8}
}
func (m *RegisterLicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLicenseRequest.Unmarshal(m, b)
}
func (m *RegisterLicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLicenseRequest.Marshal(b, m, deterministic)
}
func (m *RegisterLicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLicenseRequest.Merge(m, src)
}
func (m *RegisterLicenseRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterLicenseRequest.Size(m)
}
func (m *RegisterLicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLicenseRequest proto.InternalMessageInfo

func (m *RegisterLicenseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RegisterLicenseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterLicenseResponse) Reset()         { *m = RegisterLicenseResponse{} }
func (m *RegisterLicenseResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterLicenseResponse) ProtoMessage()    {}
func (*RegisterLicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c1f856632b222, []int{9}
}
func (m *RegisterLicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLicenseResponse.Unmarshal(m, b)
}
func (m *RegisterLicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLicenseResponse.Marshal(b, m, deterministic)
}
func (m *RegisterLicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLicenseResponse.Merge(m, src)
}
func (m *RegisterLicenseResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterLicenseResponse.Size(m)
}
func (m *RegisterLicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLicenseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateLicenseRequest)(nil), "grpc.CreateLicenseRequest")
	proto.RegisterType((*CreateLicenseResponse)(nil), "grpc.CreateLicenseResponse")
	proto.RegisterType((*ReadLicenseRequest)(nil), "grpc.ReadLicenseRequest")
	proto.RegisterType((*ReadLicenseResponse)(nil), "grpc.ReadLicenseResponse")
	proto.RegisterType((*UpdateLicenseRequest)(nil), "grpc.UpdateLicenseRequest")
	proto.RegisterType((*UpdateLicenseResponse)(nil), "grpc.UpdateLicenseResponse")
	proto.RegisterType((*DeleteLicenseRequest)(nil), "grpc.DeleteLicenseRequest")
	proto.RegisterType((*DeleteLicenseResponse)(nil), "grpc.DeleteLicenseResponse")
	proto.RegisterType((*RegisterLicenseRequest)(nil), "grpc.RegisterLicenseRequest")
	proto.RegisterType((*RegisterLicenseResponse)(nil), "grpc.RegisterLicenseResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LicenseClient is the client API for License service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LicenseClient interface {
	Create(ctx context.Context, in *CreateLicenseRequest, opts ...grpc.CallOption) (*CreateLicenseResponse, error)
	Read(ctx context.Context, in *ReadLicenseRequest, opts ...grpc.CallOption) (*ReadLicenseResponse, error)
	Update(ctx context.Context, in *UpdateLicenseRequest, opts ...grpc.CallOption) (*UpdateLicenseResponse, error)
	Delete(ctx context.Context, in *DeleteLicenseRequest, opts ...grpc.CallOption) (*DeleteLicenseResponse, error)
	Register(ctx context.Context, in *RegisterLicenseRequest, opts ...grpc.CallOption) (*RegisterLicenseResponse, error)
}

type licenseClient struct {
	cc *grpc.ClientConn
}

func NewLicenseClient(cc *grpc.ClientConn) LicenseClient {
	return &licenseClient{cc}
}

func (c *licenseClient) Create(ctx context.Context, in *CreateLicenseRequest, opts ...grpc.CallOption) (*CreateLicenseResponse, error) {
	out := new(CreateLicenseResponse)
	err := c.cc.Invoke(ctx, "/grpc.License/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Read(ctx context.Context, in *ReadLicenseRequest, opts ...grpc.CallOption) (*ReadLicenseResponse, error) {
	out := new(ReadLicenseResponse)
	err := c.cc.Invoke(ctx, "/grpc.License/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Update(ctx context.Context, in *UpdateLicenseRequest, opts ...grpc.CallOption) (*UpdateLicenseResponse, error) {
	out := new(UpdateLicenseResponse)
	err := c.cc.Invoke(ctx, "/grpc.License/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Delete(ctx context.Context, in *DeleteLicenseRequest, opts ...grpc.CallOption) (*DeleteLicenseResponse, error) {
	out := new(DeleteLicenseResponse)
	err := c.cc.Invoke(ctx, "/grpc.License/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseClient) Register(ctx context.Context, in *RegisterLicenseRequest, opts ...grpc.CallOption) (*RegisterLicenseResponse, error) {
	out := new(RegisterLicenseResponse)
	err := c.cc.Invoke(ctx, "/grpc.License/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LicenseServer is the server API for License service.
type LicenseServer interface {
	Create(context.Context, *CreateLicenseRequest) (*CreateLicenseResponse, error)
	Read(context.Context, *ReadLicenseRequest) (*ReadLicenseResponse, error)
	Update(context.Context, *UpdateLicenseRequest) (*UpdateLicenseResponse, error)
	Delete(context.Context, *DeleteLicenseRequest) (*DeleteLicenseResponse, error)
	Register(context.Context, *RegisterLicenseRequest) (*RegisterLicenseResponse, error)
}

func RegisterLicenseServer(s *grpc.Server, srv LicenseServer) {
	s.RegisterService(&_License_serviceDesc, srv)
}

func _License_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.License/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Create(ctx, req.(*CreateLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.License/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Read(ctx, req.(*ReadLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.License/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Update(ctx, req.(*UpdateLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.License/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Delete(ctx, req.(*DeleteLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _License_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.License/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServer).Register(ctx, req.(*RegisterLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _License_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.License",
	HandlerType: (*LicenseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _License_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _License_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _License_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _License_Delete_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _License_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "license.proto",
}

func init() { proto.RegisterFile("license.proto", fileDescriptor_090c1f856632b222) }

var fileDescriptor_090c1f856632b222 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x59, 0x3b, 0x15, 0xb0, 0x84, 0x00, 0xd3, 0xad, 0x5d, 0x56, 0x90, 0x95, 0x13, 0x42,
	0x24, 0x61, 0xdd, 0x0e, 0xdb, 0x4e, 0xa4, 0xe3, 0xc7, 0x24, 0x38, 0xa0, 0x02, 0x07, 0xa8, 0x26,
	0xe4, 0x26, 0xaf, 0x9e, 0x59, 0x1a, 0x07, 0xdb, 0x2d, 0xd5, 0xa6, 0x5c, 0x38, 0x72, 0x2c, 0x7f,
	0x1a, 0xff, 0x02, 0x57, 0xfe, 0x07, 0xd4, 0xc4, 0x19, 0x5a, 0x9a, 0x5d, 0xb7, 0x53, 0x1c, 0xfb,
	0xbd, 0xf7, 0xf9, 0xc6, 0xef, 0xfb, 0x82, 0xee, 0x44, 0x3c, 0x80, 0x58, 0x81, 0x9b, 0x48, 0xa1,
	0x05, 0x5e, 0x65, 0x32, 0x09, 0xac, 0x0e, 0x13, 0x82, 0x45, 0xe0, 0xd1, 0x84, 0x7b, 0x34, 0x8e,
	0x85, 0xa6, 0x9a, 0x8b, 0x58, 0xe5, 0x31, 0xd6, 0xd3, 0xec, 0x11, 0x38, 0x0c, 0x62, 0x47, 0x7d,
	0xa7, 0x8c, 0x81, 0xf4, 0x44, 0x92, 0x45, 0x2c, 0x47, 0xdb, 0x33, 0xd4, 0x3c, 0x90, 0x40, 0x35,
	0xbc, 0xcd, 0x41, 0x7d, 0xf8, 0x36, 0x01, 0xa5, 0xf1, 0x00, 0xd5, 0x78, 0xd8, 0x5e, 0x21, 0x2b,
	0x8f, 0x6f, 0xf7, 0xde, 0xcc, 0xfd, 0xc3, 0x9f, 0x2b, 0x2f, 0x07, 0xcf, 0x9c, 0x3d, 0xdf, 0x79,
	0x75, 0x74, 0xb6, 0x9b, 0x3a, 0xe7, 0xeb, 0x9d, 0xd4, 0x19, 0xec, 0x1c, 0x9d, 0xbf, 0x6e, 0xa7,
	0xce, 0x60, 0x77, 0xcf, 0xef, 0x5d, 0xdc, 0x29, 0xd6, 0x5b, 0xdd, 0xb4, 0x5f, 0xe3, 0xe1, 0x7e,
	0x7d, 0xee, 0xdf, 0xb0, 0x5b, 0x68, 0xad, 0x44, 0x56, 0x89, 0x88, 0x15, 0xd8, 0x53, 0x84, 0xfb,
	0x40, 0xc3, 0x2b, 0x17, 0xb4, 0x86, 0x1e, 0x5c, 0xe0, 0x1a, 0x39, 0x33, 0xd4, 0xfc, 0x98, 0x84,
	0xd7, 0x74, 0x43, 0x25, 0xf2, 0x7f, 0x49, 0x2f, 0x20, 0x82, 0xeb, 0x91, 0x54, 0x22, 0x1b, 0x49,
	0xa7, 0x68, 0xbd, 0x0f, 0x8c, 0x2b, 0x0d, 0xf2, 0xca, 0x45, 0x6d, 0xa0, 0xd6, 0x12, 0x3b, 0x97,
	0xd5, 0xfd, 0x5b, 0x47, 0x37, 0xcd, 0x1e, 0xfe, 0x8c, 0x1a, 0xb9, 0xe1, 0xb0, 0xe5, 0x2e, 0xe6,
	0xc8, 0xad, 0x32, 0xbe, 0xb5, 0x59, 0x79, 0x66, 0xbe, 0xb2, 0xf5, 0xe3, 0xf7, 0x9f, 0x5f, 0xb5,
	0xfb, 0xf6, 0xdd, 0x6c, 0xf6, 0xa6, 0x5b, 0x9e, 0x19, 0x4f, 0xfc, 0x09, 0xad, 0x2e, 0xbc, 0x83,
	0xdb, 0x79, 0xf6, 0xb2, 0x7f, 0xad, 0x8d, 0x8a, 0x13, 0x53, 0xb5, 0x93, 0x55, 0x5d, 0xc7, 0xcd,
	0x52, 0x55, 0xef, 0x8c, 0x87, 0x29, 0xfe, 0x82, 0x1a, 0xb9, 0x0b, 0x0a, 0xd9, 0x55, 0x6e, 0x2c,
	0x64, 0x57, 0xfb, 0xc5, 0x00, 0xac, 0x4b, 0x01, 0x79, 0x4f, 0x0b, 0x40, 0x95, 0xb7, 0x0a, 0x40,
	0x75, 0xf7, 0x0d, 0xe0, 0x49, 0x35, 0x80, 0xa3, 0x5b, 0x45, 0x7f, 0x70, 0xa7, 0xb8, 0x86, 0x2a,
	0xaf, 0x58, 0x0f, 0x2f, 0x39, 0x35, 0x18, 0x92, 0x61, 0x2c, 0xbb, 0x5d, 0xc6, 0x48, 0x93, 0xd0,
	0x4b, 0xe7, 0xfe, 0x29, 0x9e, 0xa1, 0x4d, 0x3f, 0x08, 0x40, 0x29, 0x72, 0x20, 0x62, 0x2d, 0x45,
	0x44, 0xa8, 0x22, 0x94, 0xbc, 0x07, 0x39, 0xe5, 0x01, 0xd8, 0x1f, 0xd0, 0xa3, 0xd7, 0x13, 0x2a,
	0x43, 0x92, 0x48, 0xf1, 0x15, 0x02, 0x4d, 0xc4, 0x88, 0x1c, 0x4e, 0x98, 0x22, 0xef, 0x22, 0xaa,
	0x47, 0x42, 0x8e, 0x31, 0x39, 0xd6, 0x3a, 0x51, 0xfb, 0x9e, 0xc7, 0xb8, 0x3e, 0x9e, 0x0c, 0xdd,
	0x40, 0x8c, 0xbd, 0x13, 0x3a, 0xe6, 0x91, 0x3a, 0xf1, 0xd8, 0x22, 0xd5, 0xba, 0xc7, 0xe3, 0x91,
	0x78, 0x2e, 0x02, 0x2d, 0x22, 0x3a, 0x74, 0x85, 0x64, 0xdd, 0x7a, 0x08, 0xd3, 0x61, 0x23, 0xfb,
	0xa9, 0x6e, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xf7, 0xfc, 0x5f, 0xb7, 0x05, 0x00, 0x00,
}
